name: Test
on:
  push:
    branches:
      - main

jobs:
  build: # create a test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Create a release draft for version tag
        id: create-release-draft
        uses: ./
      - name: Print theURL of the release draft
        run: echo ${{ steps. create-release-draft.output.relase-url }}